### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by josharian** [zoul/UILabel-Clipboard-Sample#2]
It's really stupid, I know, but would you mind terribly throwing a license file in this repo? Thanks!

**Comment by zoul** [comment]
The code is public domain, I’ve added a link to the [CC0 license text](http://creativecommons.org/publicdomain/zero/1.0/legalcode) to the readme. Hope that helps.

**Comment by josharian** [comment]
Thanks, much appreciated!
